#spring.profiles.active=tomcat, hide, h2, jpa_update
#spring.profiles.active=tomcat, hide, h2, jpa_create
spring.profiles.active=tomcat, hide, h2, jpa_validate

#spring.mustache.expose-request-attributes=true

#dev=false

#spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#spring.jpa.hibernate.naming.implicit-strategy=org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl

