CREATE TABLE assignments (
    id bigint generated by default as identity,
    assoc_form_name bigint,
    assoc_name varchar(150) not null,
    assoc_spec_id bigint not null,
    assoc_wo_name varchar(100),
    dependent_flag boolean not null,
    form_name bigint,
    spec_id bigint not null,
    wo_name varchar(100),
    primary key (id) );
CREATE TABLE wo_state (
    id bigint generated by default as identity,
    wo_name varchar(100) not null,
    wo_state varchar(100) not null,
    primary key (id) );
CREATE TABLE wo_state_transition (
    id bigint generated by default as identity,
    action_label varchar(100) not null,
    action_name varchar(100) not null,
    class_name varchar(1000),
    close_screan boolean not null,
    current_state varchar(100) not null,
    custom_url varchar(500),
    method_name varchar(100),
    next_state varchar(100) not null,
    read_only boolean not null,
    secondary_action boolean not null,
    wo_name varchar(100) not null,
    primary key (id) );
