create table t_people (spec_id bigint generated by default as identity, w_family_nametx varchar(150) not null, w_first_nametx varchar(150) not null, w_surnametx varchar(100) not null, primary key (spec_id));
INSERT INTO wo_state(wo_name, wo_state)
     VALUES ('wPeople', 'null'),
            ('wPeople', 'wDraft'),
            ('wPeople', 'wActive'),
            ('wPeople', 'wRetired');
INSERT INTO wo_state_transition(
        wo_name, current_state, next_state, action_name, action_label, class_name, close_screan, read_only, secondary_action)
VALUES ('wPeople', 'null', 'wDraft', 'wCreate', 'Create', 'wPeople - Synchronous - when Create', FALSE, FALSE, FALSE),
       ('wPeople', 'wDraft', 'wActive','wActivate', 'Activate', NULL, FALSE, FALSE, TRUE),
       ('wPeople', 'wDraft', 'wRetired', 'wRetire', 'Retire', NULL, FALSE, FALSE, FALSE),
       ('wPeople', 'wActive', 'wRetire', 'wRetire', 'Retire', NULL, FALSE, FALSE, FALSE),
       ('wPeople', 'wRetire', 'null', 'wDelete', 'Delete', NULL, FALSE, FALSE, FALSE);
create table t_myprofile (spec_id bigint generated by default as identity, w_family_nametx varchar(150) not null, w_first_nametx varchar(150) not null, w_surnametx varchar(100) not null, w_usernametx varchar(100) not null, primary key (spec_id));
INSERT INTO wo_state(wo_name, wo_state)
     VALUES ('wMyProfile', 'null'),
            ('wMyProfile', 'wDraft'),
            ('wMyProfile', 'wActive'),
            ('wMyProfile', 'wRetired');
